/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        /* Theme tokens (CSS variables in src/index.css) */
        canvas: 'rgb(var(--canvas) / <alpha-value>)',
        'canvas-2': 'rgb(var(--canvas-2) / <alpha-value>)',
        surface: 'rgb(var(--surface) / <alpha-value>)',
        'surface-2': 'rgb(var(--surface-2) / <alpha-value>)',
        'surface-3': 'rgb(var(--surface-3) / <alpha-value>)',
        hi: 'rgb(var(--hi) / <alpha-value>)',
        fg: 'rgb(var(--fg) / <alpha-value>)',
        'fg-soft': 'rgb(var(--fg-soft) / <alpha-value>)',
        'fg-2': 'rgb(var(--fg-2) / <alpha-value>)',
        'fg-lav': 'rgb(var(--fg-lav) / <alpha-value>)',
        'fg-3': 'rgb(var(--fg-3) / <alpha-value>)',
        'fg-4': 'rgb(var(--fg-4) / <alpha-value>)',
        ink: 'rgb(var(--ink) / <alpha-value>)',
        primary: {
          DEFAULT: '#7C5CFC',
          light: '#9B7FFF',
          dark: '#6341E0',
        },
        purple: {
          DEFAULT: '#8B5CF6',
          light: '#A78BFA',
          dark: '#7C3AED',
        },
        accent: {
          DEFAULT: '#00D4AA',
          light: '#34EDCA',
          dark: '#00B894',
        },
        warning: {
          DEFAULT: '#FF6B6B',
          light: '#FCA5A5',
          dark: '#EF4444',
        },
        surface: {
          dark: '#060918',
          mid: '#0A0E1F',
          light: '#0F1329',
          card: '#111633',
          deep: '#030712',
        },
        land: {
          bg: '#060918',
          card: '#0F1329',
          border: 'rgba(124,92,252,0.12)',
          text: '#F0EEFF',
          muted: '#8B8AA8',
          subtle: '#141938',
          // dark mode (always dark in redesign)
          'dark-bg': 'rgb(var(--canvas) / <alpha-value>)',
          'dark-card': 'rgb(var(--surface) / <alpha-value>)',
          'dark-border': 'rgba(124,92,252,0.12)',
          'dark-text': 'rgb(var(--fg) / <alpha-value>)',
          'dark-muted': 'rgb(var(--fg-lav) / <alpha-value>)',
          'dark-subtle': '#141938',
        },
        dash: {
          bg: 'rgb(var(--canvas) / <alpha-value>)',
          sidebar: '#0A0E1F',
          card: 'rgb(var(--surface) / <alpha-value>)',
          border: 'rgba(124,92,252,0.1)',
          'border-light': 'rgba(124,92,252,0.2)',
          hover: 'rgba(124,92,252,0.06)',
          text: 'rgb(var(--fg) / <alpha-value>)',
          muted: 'rgb(var(--fg-2) / <alpha-value>)',
          accent: '#7C5CFC',
        },
        sage: {
          DEFAULT: '#7C5CFC',
          light: '#9B7FFF',
          dark: '#6341E0',
          50: 'rgba(124,92,252,0.08)',
          100: 'rgba(124,92,252,0.14)',
        },
        neon: {
          purple: '#7C5CFC',
          cyan: '#00D4AA',
          pink: '#FF6B9D',
          blue: '#4FACFE',
        },
      },
      fontFamily: {
        sans: [
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'sans-serif',
        ],
      },
      borderRadius: {
        glass: '20px',
        pill: '9999px',
        '2xl': '16px',
        '3xl': '24px',
        '4xl': '32px',
      },
      backdropBlur: {
        glass: '24px',
        ultra: '40px',
      },
      boxShadow: {
        glass: '0 8px 32px rgba(0, 0, 0, 0.2)',
        glow: '0 0 30px rgba(124, 92, 252, 0.35)',
        'glow-sm': '0 0 15px rgba(124, 92, 252, 0.2)',
        'glow-accent': '0 0 30px rgba(0, 212, 170, 0.3)',
        'glow-lg': '0 0 60px rgba(124, 92, 252, 0.4)',
        'card-soft': '0 4px 24px rgba(0, 0, 0, 0.3)',
        'card-hover': '0 12px 48px rgba(124, 92, 252, 0.15)',
        'window': '0 16px 64px rgba(0, 0, 0, 0.5), 0 0 0 1px rgba(124, 92, 252, 0.1)',
        'dash-sm': '0 1px 2px rgba(0,0,0,0.1)',
        'dash-card': '0 4px 24px rgba(0, 0, 0, 0.3)',
        'inner-glow': 'inset 0 1px 1px rgba(255, 255, 255, 0.05)',
        'neon': '0 0 20px rgba(124, 92, 252, 0.5), 0 0 40px rgba(124, 92, 252, 0.2)',
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'float-delayed': 'float 6s ease-in-out 2s infinite',
        'float-slow': 'float 8s ease-in-out infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'pulse-glow': 'pulseGlow 3s ease-in-out infinite',
        'gradient-shift': 'gradientShift 8s ease infinite',
        'fade-in': 'fadeIn 0.5s ease-out forwards',
        'spin-slow': 'spin 12s linear infinite',
        'aurora': 'aurora 15s ease infinite',
        'shimmer': 'shimmer 2.5s linear infinite',
        'beam': 'beam 3s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-15px)' },
        },
        gradientShift: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pulseGlow: {
          '0%, 100%': { opacity: '0.4', transform: 'scale(1)' },
          '50%': { opacity: '0.8', transform: 'scale(1.05)' },
        },
        aurora: {
          '0%, 100%': { transform: 'translate(0, 0) rotate(0deg)' },
          '33%': { transform: 'translate(30px, -20px) rotate(120deg)' },
          '66%': { transform: 'translate(-20px, 20px) rotate(240deg)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        beam: {
          '0%, 100%': { opacity: '0.3', transform: 'translateX(-100%)' },
          '50%': { opacity: '0.8', transform: 'translateX(100%)' },
        },
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, #7C5CFC, #4FACFE)',
        'gradient-accent': 'linear-gradient(135deg, #00D4AA, #4FACFE)',
        'gradient-surface': 'linear-gradient(180deg, #0F1329, #060918)',
        'gradient-surface-dark': 'linear-gradient(180deg, #111827, #0B0F19)',
        'gradient-hero': 'radial-gradient(ellipse at 50% 0%, rgba(124, 92, 252, 0.15) 0%, transparent 60%)',
        'gradient-card': 'linear-gradient(135deg, rgba(124, 92, 252, 0.05), rgba(79, 172, 254, 0.03))',
        'gradient-mesh': 'radial-gradient(at 40% 20%, rgba(124, 92, 252, 0.08) 0px, transparent 50%), radial-gradient(at 80% 0%, rgba(0, 212, 170, 0.06) 0px, transparent 50%), radial-gradient(at 0% 50%, rgba(79, 172, 254, 0.06) 0px, transparent 50%)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    // `light:` variant — one-off tweaks for the light theme (html.light, see ThemeContext)
    ({ addVariant }) => addVariant('light', 'html.light &'),
  ],
};
